=== Wyper13/XML/config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT mv:query ((mv:id)*, (mv:random)*, (mv:include)?, (mv:exclude)?)>
<!ATTLIST mv:query xmlns:mv CDATA #FIXED "http://moviesRT">
<!ELEMENT mv:id (#PCDATA)>
<!ELEMENT mv:random (#PCDATA)>
<!ELEMENT mv:include ((mv:prop)+)>
<!ELEMENT mv:exclude ((mv:prop)+)>
<!ELEMENT mv:prop (#PCDATA)>

=== Wyper13/XML/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mv:query SYSTEM "config.dtd">
<!-- On ne fait pas de queries / query puisqu'on fait une union aprÃ¨s ... -->
<mv:query xmlns:mv="http://moviesRT">
	<mv:id>120</mv:id>
	<mv:id>121</mv:id>
	<mv:random>5</mv:random>
	<mv:id>122</mv:id>
	<mv:id>123</mv:id>
	<mv:random>3</mv:random>
	<mv:include>
		<mv:prop>title</mv:prop>
		<mv:prop>runtime</mv:prop>
		<mv:prop>vote_average</mv:prop>
		<mv:prop>vote_count</mv:prop>
	</mv:include>
	<mv:exclude>
		<mv:prop>overview</mv:prop>
	</mv:exclude>
</mv:query>
